# action name
name: Tests with Jest

# when to fire the action
on:
  push:
    branches: [ master ]

# what to do
jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
    - run: npm install
    - run: npm run test:type-check
    - run: npm run test:jest
