# action name
name: Tests in Pull Requests

# when to fire the action
on:
  pull_request:
    branches: [ master ]

# what to do
jobs:
  coverage:
    runs-on: ubuntu-latest

steps:
  uses: ArtiomTr/jest-coverage-report-action@v2.0
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    test-script: npm run test:coverage-ci